### ISSUE TITLE
Documentation is not being generated unless defaults is specified

### ISSUE THREAD

**Issue by petarcurkovic** [Stankec/Rocket_Docs#3]
Hi!

I'm getting an empty doc page unless I specify default version in the routes.rb file.
What I have to do:
```Ruby
namespace :api do
    mount RocketDocs::Engine => '/doc'
    api version: 1, module: 'v1', defaults: { version: 'v1' } do
    end
end
```

What I would expect:
```Ruby
namespace :api do
    mount RocketDocs::Engine => '/doc'
    api version: 1, module: 'v1' do
    end
end
```

**Comment by Stankec** [comment]
I have updated the gem.
Now only a version will suffice, so that this will work:
```Ruby
namespace :api do
    mount RocketDocs::Engine => '/doc'
    api version: 1 do # additionally a module or defaults can be defined here
    end
end
```

By solving this issue another one has been closed also.
I'm talking about multi version routs not being recognised as such. E.g.
```Ruby
namespace :api do
    mount RocketDocs::Engine => '/doc'
    api version: 1..3, module: 'v1', defaults: { version: 1 } do
    end
end
```
In the past this would only register version 3, but now it correctly registers versions 1 through 3.
Please check and report back if this change is to your liking :)

**Comment by petarcurkovic** [comment]
It works!

Thanks!
